#!/usr/bin/php
<?php

$DBNAME = null;
$outFile = 'output.sql';
$collationName = 'utf8_general_ci';
if (true == array_key_exists(1, $argv)) {
    $DBNAME = $argv[1];
}
if (true == array_key_exists(2, $argv)) {
    $outFile = $argv[2];
} 
if (true == array_key_exists(3, $argv)) {
    $collationName = $argv[3];
}

if (false === empty($DBNAME) && false === empty($outFile) && false === empty($collationName)) {
    generateScript($DBNAME, $collationName, $outFile);
} else {
    echo "\nDBUTF8 Version 0.1 \n";
    echo "Copyright (C) 2014, Mozart\n\n";
    echo "A script generator for conversion of MySQL DB collation for UTF-8 charset\n";
    echo "Usage:\tdbutf8.php database_name [output.sql] [collation_name]\n\n";
    echo "Default collation is 'utf8_general_ci'\n";
    echo "Run this script as root\n";
}

exit(1);


function generateScript($DBNAME, $collationName, $outFile)
{
    $sql = '';
    $sql = $sql . "USE $DBNAME;\n";
    $sql = $sql . "ALTER DATABASE $DBNAME CHARSET utf8 COLLATE {$collationName};\n";
    $sql = $sql . "SET AUTOCOMMIT = 0; SET FOREIGN_KEY_CHECKS = 0; SET UNIQUE_CHECKS = 0;\n";
    $sql = $sql . "START TRANSACTION;\n";
    exec('mysql -BNe "SHOW TABLE STATUS FROM ' . $DBNAME . ' WHERE \`Engine\` IS NOT NULL;" '
        . '| awk \'{print("ALTER TABLE `\'' . $DBNAME . '\'`.`"$1"` CONVERT TO CHARACTER SET utf8 COLLATE ' . $collationName . ';");}\'', $output);
    $sql = $sql . join("\n", $output);
    $sql = $sql . "\n\nCOMMIT;\n";
    $sql = $sql . "SET AUTOCOMMIT = 1; SET FOREIGN_KEY_CHECKS = 1; SET UNIQUE_CHECKS = 1;\n";

    $output = array();
    exec("mysqldump --no-create-db --no-create-info --no-data --routines --triggers=0 $DBNAME", $output);
    array_walk($output, function(& $val) {
        //            
        if (false !== stripos($val, 'ALTER DATABASE')) {
            $val = ""; // removing any database altering
        } else {
            $val = preg_replace('@^.*?(DROP\s+(PROCEDURE|FUNCTION)\s+IF\s+EXISTS\s+`[^`]+`).*?$@is', '$1;', $val);
            $val = preg_replace('/DEFINER=`[^`]+`@`[^`]+`/is', '', $val);
            $val = preg_replace('@COLLATE\s+[a-z0-9_]+@is', '', $val);
        }
    });
    $sql = $sql . "\n\n\n" . join("\n", $output);
    
    file_put_contents($outFile, $sql);
}
